"""create module entitlement and sidebar menu tables

Revision ID: ab5b4456fa52
Revises: 7c2d0b3c2f9a
Create Date: 2026-04-27 09:21:28.155150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5b4456fa52'
down_revision: Union[str, Sequence[str], None] = '7c2d0b3c2f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=80), nullable=False),
    sa.Column('module_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('menu_group', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(module_key)) > 0', name='ck_app_modules_module_key_not_empty'),
    sa.CheckConstraint('length(trim(module_name)) > 0', name='ck_app_modules_module_name_not_empty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_key'),
    sa.UniqueConstraint('module_key', name='uq_app_modules_module_key')
    )
    op.create_table('sidebar_menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=80), nullable=False),
    sa.Column('group_key', sa.String(length=80), nullable=False),
    sa.Column('item_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('route_path', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('requires_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(group_key)) > 0', name='ck_sidebar_menu_items_group_key_not_empty'),
    sa.CheckConstraint('length(trim(item_key)) > 0', name='ck_sidebar_menu_items_item_key_not_empty'),
    sa.CheckConstraint('length(trim(label)) > 0', name='ck_sidebar_menu_items_label_not_empty'),
    sa.CheckConstraint('length(trim(route_path)) > 0', name='ck_sidebar_menu_items_route_path_not_empty'),
    sa.ForeignKeyConstraint(['module_key'], ['app_modules.module_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_key', 'item_key', name='uq_sidebar_menu_items_module_item')
    )
    op.create_table('entity_module_entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'suspended', 'expired')", name='ck_entity_module_entitlements_status'),
    sa.ForeignKeyConstraint(['enabled_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['module_key'], ['app_modules.module_key'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'module_key', name='uq_entity_module_entitlements_entity_module')
    )
    op.drop_table('sidebar_menu_settings')
    op.alter_column('entities', 'profile_scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('uq_entities_internal_number'), table_name='entities', postgresql_where='(internal_number IS NOT NULL)')
    op.drop_index(op.f('uq_entities_single_owner_scope'), table_name='entities', postgresql_where="((profile_scope)::text = 'owner'::text)")
    op.create_unique_constraint(None, 'entities', ['internal_number'])
    op.alter_column('members', 'whatsapp_verification_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'whatsapp_notice_opt_in',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'whatsapp_last_check_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('members', 'training_discipulado_verbo_vida',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'training_ebvv',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'training_rhema',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'training_escola_ministerial',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('members', 'training_escola_missoes',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'training_escola_missoes',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'training_escola_ministerial',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'training_rhema',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'training_ebvv',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'training_discipulado_verbo_vida',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'whatsapp_last_check_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('members', 'whatsapp_notice_opt_in',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('members', 'whatsapp_verification_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'unknown'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'entities', type_='unique')
    op.create_index(op.f('uq_entities_single_owner_scope'), 'entities', ['profile_scope'], unique=True, postgresql_where="((profile_scope)::text = 'owner'::text)")
    op.create_index(op.f('uq_entities_internal_number'), 'entities', ['internal_number'], unique=True, postgresql_where='(internal_number IS NOT NULL)')
    op.alter_column('entities', 'profile_scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'legado'::character varying"),
               existing_nullable=False)
    op.create_table('sidebar_menu_settings',
    sa.Column('menu_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('menu_label', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('menu_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('menu_key', name=op.f('sidebar_menu_settings_pkey'))
    )
    op.drop_table('entity_module_entitlements')
    op.drop_table('sidebar_menu_items')
    op.drop_table('app_modules')
    # ### end Alembic commands ###
