"""create module entitlement and sidebar menu tables

Revision ID: fc2cca3e78f6
Revises: ab5b4456fa52
Create Date: 2026-04-27 09:26:10.537587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2cca3e78f6'
down_revision: Union[str, Sequence[str], None] = 'ab5b4456fa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
